Network
Benjamin-A/Heislab pull request #48
Opened 2024-03-07 15:03 UTC by mikitecle

2024-03-08 11:14 UTC, Kytzis requested changes

2024-03-08 11:14 UTC, Kytzis commented on The-ELEVATOR/network-go/network/bcast/bcast.go
Denne trenger vel ikke endres dersom vi bare baserer oss på peers.go? Kan utelate fila fra merge isåfall, så vi ikke ser ut som vi har endra og bruker ting vi ikke gjør

2024-03-08 11:14 UTC, Kytzis commented on The-ELEVATOR/network-go/network/peers/peers.go
> +			e.ID = ID
Dersom ID settes i nettverk modulen, kan jo txChan være av typen chan structs.OrderMatrix? Da slipper ordre modulen å bry seg med hvordan nettverk pakken ser ut under avsending

2024-03-08 11:14 UTC, Kytzis commented on The-ELEVATOR/network-go/network/peers/peers.go
> +		peerUpdateCh <- receivedOrder
peerUpdateCh er et dårlig navn når vi sender hele den mottatte pakken. receivedOrder får det også til å virke som vi mottar én ordre, mens vi i realiteten mottar hele lista med ordre som en heis vet om

2024-03-08 11:14 UTC, Kytzis commented on The-ELEVATOR/network/network.go
> +				txCh <- ourState
Maybe a small comment to say this solves not sedning junk data during init?

2024-03-08 11:14 UTC, Kytzis commented on The-ELEVATOR/orders/orders.go
Mye TODO her, men det er min feil. Good som det er, trenger dette som palceholder for å jobbe videre

2024-03-08 11:14 UTC, Kytzis commented on The-ELEVATOR/structs/structs.go
Fjern alle leftover kommentarer av gamle fields <3

2024-03-08 12:51 UTC, Benjamin-A commented on The-ELEVATOR/network-go/network/peers/peers.go
>  const timeout = 500 * time.Millisecond
perhaps base this on interval?

2024-03-08 12:52 UTC, Benjamin-A commented on The-ELEVATOR/network-go/network/peers/peers.go
>  const timeout = 500 * time.Millisecond
that would require it to not be a const....

2024-03-08 12:58 UTC, Benjamin-A reviewed
I agree with @Kytzis. implement the changes and then we are good

2024-03-08 13:01 UTC, sanntid commented on The-ELEVATOR/network-go/network/peers/peers.go
> +		peerUpdateCh <- receivedOrder
er det bare legge til en "s" da, peersUpdateCh, og recivedOrders?

2024-03-10 14:27 UTC, mikitecle commented on The-ELEVATOR/network-go/network/bcast/bcast.go
Skal jeg slette bcast,fila og main.fila fra Network-go mappen?

2024-03-12 11:28 UTC, Kytzis approved these changes
lgtm

2024-03-12 11:59 UTC, merged