52 watchdog dagger
Benjamin-A/Heislab pull request #58
Opened 2024-03-12 12:45 UTC by Benjamin-A

2024-03-14 13:55 UTC, Kytzis requested changes

2024-03-14 13:55 UTC, Kytzis commented on The-ELEVATOR/elevDriver/elevDriver.go
>  	go elevatorControlThread(newOrder, arrivedAtFloor, stateUpdated, changedState)
shouldnt they both have an health update?

2024-03-14 13:55 UTC, Kytzis commented on The-ELEVATOR/elevDriver/elevDriver.go
> +			print("No elevDriver event received for 500 milliseconds")
first of all this is a syntax error, but dont print, just add a continue

2024-03-14 13:55 UTC, Kytzis commented on The-ELEVATOR/buttons/buttons.go
> +			print("No button event received for 500 milliseconds")
change with continue before merge

2024-03-14 13:55 UTC, Kytzis commented on The-ELEVATOR/network/network.go
> +		networkThreadHealthUpdate <- 1
Id rather see this happen inside the Rx and Tx threads that actually do something and can lockup

2024-03-14 13:55 UTC, Kytzis commented on The-ELEVATOR/network/network.go
> +			print("No network event received for 500 milliseconds")
continue

2024-03-14 13:55 UTC, Kytzis commented on The-ELEVATOR/orders/orders.go
> +			fmt.Println("New Order")
logger

2024-03-14 13:55 UTC, Kytzis commented on The-ELEVATOR/orders/orders.go
> +			fmt.Println("New Driver State")
logger

2024-03-14 13:55 UTC, Kytzis commented on The-ELEVATOR/orders/orders.go
> +			print("No order event received for 500 milliseconds")
continue

2024-03-14 13:55 UTC, Kytzis commented on The-ELEVATOR/watchdog/watchdog.go
> +				logger.Error("MAIN", "Killing this primary process pair\n")
"Committing Seppuku" isntead?

2024-03-14 13:55 UTC, Kytzis commented on The-ELEVATOR/watchdog/watchdog.go
> +		logger.Info("WATCHDOG", fmt.Sprintf("Main: %d Buttons: %d Orders: %d ElevDriver: %d Network: %d", countMain, countButtons, countOrders, countElevDriver, countNetwork))
Make sure to add WATCHDOG as a thread in logger, maybe also use PascalCase as we do with the other threads in logger (excpt main >:( )

2024-03-14 14:40 UTC, Benjamin-A commented on The-ELEVATOR/elevDriver/elevDriver.go
> +			print("No elevDriver event received for 500 milliseconds")
strangely enough, it works 🤔. Will replace with logger

2024-03-14 14:52 UTC, Benjamin-A commented on The-ELEVATOR/network/network.go
> +		networkThreadHealthUpdate <- 1
yes

2024-03-14 16:55 UTC, Kytzis commented
Also make sure to do some thorough testing before merging as always

2024-03-15 12:02 UTC, Kytzis approved these changes
lgtm

2024-03-15 12:10 UTC, Kytzis approved these changes

2024-03-15 12:11 UTC, merged